services:
  mysql:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_DATABASE: sinergy
      MYSQL_ROOT_PASSWORD: mysqlroot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/sinergy
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysqlroot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped

volumes:
  mysql_data:
      


