services:
  auth-db:
    image: mysql:8
    container_name: auth-db
    restart: always
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: mysqlauth
      MYSQL_ROOT_PASSWORD: mysqlroot
    ports:
      - "3307:3306"
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - sinergy-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pmysqlroot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-db:
    image: mysql:8
    container_name: user-db
    restart: always
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: user_user
      MYSQL_PASSWORD: mysqluser
      MYSQL_ROOT_PASSWORD: mysqlroot
    ports:
      - "3308:3306"
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - sinergy-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pmysqlroot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  auth-service:
    build:
      context: ./server/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://auth-db:3306/auth_db?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: auth_user
      SPRING_DATASOURCE_PASSWORD: mysqlauth
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - sinergy-network

  user-service:
    build:
      context: ./server/user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/user_db?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user_user
      SPRING_DATASOURCE_PASSWORD: mysqluser
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - sinergy-network

networks:
  sinergy-network:

volumes:
  auth-db-data:
  user-db-data:
      


