name: pipeline server

on:
  push:
  #   branches: [ main, dev ]
  # pull_request:
  #   branches: [ main, dev ]
    paths:
      - 'server/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      # cloning repository
      - uses: actions/checkout@v4

      # - name: build docker image
      #   run: docker build -t auth-service .

      - name: tests
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: mvn clean verify

