name: pipeline server

on:
  push:
  #   branches: [ main, dev ]
  # pull_request:
  #   branches: [ main, dev ]
    paths:
      - 'server/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        # add other services over time
        service: [auth-service, user-service]

    steps:
      # cloning repository
      - uses: actions/checkout@v4

      # - name: build docker image
      #   run: docker build -t auth-service .

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: run tests
        working-directory: ./server/${{ matrix.service }}
        run: mvn clean verify

